# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160327_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_dir',
            name='categories',
        ),
    ]
