# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160327_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_dir',
            name='id_CO',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Specialization'),
        ),
    ]
