# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20160327_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_dir',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='course_dir',
            name='updated_date',
        ),
    ]
