# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
