# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_specialization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dir',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
