# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 21:52
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_dir_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=courses.models.image_upload_to)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course_dir')),
            ],
        ),
    ]
