# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_dir',
            name='img',
        ),
    ]
