# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_attendance_sheet_course_watch_later'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_attendance_sheet',
            name='course',
        ),
        migrations.AddField(
            model_name='course_attendance_sheet',
            name='course',
            field=models.ManyToManyField(blank=None, default=None, null=True, to='courses.Course_dir'),
        ),
        migrations.RemoveField(
            model_name='course_watch_later',
            name='course',
        ),
        migrations.AddField(
            model_name='course_watch_later',
            name='course',
            field=models.ManyToManyField(blank=None, default=None, null=True, to='courses.Course_dir'),
        ),
    ]
